---
deployment:
  tasks:
    - export DEPLOYPATH=/home/amcdouga/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp Images $DEPLOYPATH
    - index.html $DEPLOYPATH
    - style.css $DEPLOYPATH
    - Images $DEPLOYPATH
